#!/usr/bin/env python3
import sys
import pullissue.app as load

logging.basicConfig(level=logging.DEBUG,
                    format='%(name)s - %(levelname)s - %(message)s')

if len(sys.argv) > 3:
    token = sys.argv[1]
    repository = sys.argv[2]
    dir = sys.argv[3]
    load.loadSingleRepository(token, repository, dir)
