#!/usr/bin/env python3
import sys

if len(sys.argv) > 3:
    import pullissue.app as load

    token = sys.argv[1]
    repository = sys.argv[2]
    dir = sys.argv[3]
    load.loadSingleRepository(token, repository, dir)
